---
title: "Classifying synthetic ordinal data using Decision Trees (rpartscore)"
author: "James Twose"
output: html_notebook
---


```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(parsnip)
library(magrittr)
library(dplyr)
library(faux)
library(DataExplorer)
library(caret)
library(randomForest)
library(tidyr)
library(cvms)
library(doParallel)
library(rattle)
library(rpart)
```

```{r}
sessionInfo()
```

```{r}
df <- read.csv("data/synthetic_likert_data.csv")
```

```{r, fig.height=15, fig.width=15}
# Exploratory data analysis
plot_intro(df)
plot_bar(df)
plot_correlation(df)
```

```{r}
grouping_var <- "target"
feature_list <- colnames(df[, !(names(df) %in% c(grouping_var, "X"))])

# dput(as.character(feature_list))
# dput(as.character(rep("unordered", 10)))
```

```{r}
ordering_lookup <- data.frame(
  varname = c("likert_5_options_0", "likert_5_options_1", "likert_5_options_2", 
"likert_5_options_3", "likert_5_options_4", "likert_5_options_5", 
"likert_5_options_6", "likert_5_options_7", "likert_5_options_8", 
"likert_5_options_9", "likert_5_options_10", "likert_5_options_11", 
"likert_5_options_12", "likert_5_options_13", "likert_5_options_14", 
"likert_5_options_15", "likert_5_options_16", "likert_5_options_17", 
"likert_5_options_18", "likert_5_options_19", "likert_5_options_20", 
"likert_5_options_21", "likert_5_options_22", "likert_5_options_23", 
"likert_5_options_24", "likert_5_options_25", "likert_5_options_26", 
"likert_5_options_27", "likert_5_options_28", "likert_5_options_29", 
"likert_5_options_30", "likert_5_options_31", "likert_5_options_32", 
"likert_5_options_33", "likert_5_options_34", "likert_5_options_35", 
"likert_5_options_36", "likert_5_options_37", "likert_5_options_38", 
"likert_5_options_39", "likert_7_options_0", "likert_7_options_1", 
"likert_7_options_2", "likert_7_options_3", "likert_7_options_4", 
"likert_7_options_5", "likert_7_options_6", "likert_7_options_7", 
"likert_7_options_8", "likert_7_options_9", "likert_2_options_0", 
"likert_2_options_1", "likert_2_options_2", "likert_2_options_3", 
"likert_2_options_4", "likert_2_options_5", "likert_2_options_6", 
"likert_2_options_7", "likert_2_options_8", "likert_2_options_9"
),
  ordering = c("ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "ordered", "ordered", "ordered", "ordered", 
"ordered", "ordered", "unordered", "unordered", "unordered", "unordered", "unordered", 
"unordered", "unordered", "unordered", "unordered", "unordered")
)
```

```{r}
# if (grouping_var == "behaviour_unmasked") {
#   # df <- df %>% mutate(tmp = if_else(!!as.symbol(grouping_var) != 5, 'bad', 'good'))
#   df <- df %>% mutate(tmp = if_else(!!as.symbol(grouping_var) != 5, 0, 1))
# 
#   names(df)[names(df) == 'tmp'] <- paste0(grouping_var, "_bool")
# }
    
```

```{r}
df[, grouping_var] <- as.factor(df[, grouping_var])
```

```{r}
# df %<>%
#        mutate_each_(funs(factor(.)), colnames(df))
# str(df)

ordinal_vars_mydata <- ordering_lookup %>%
  dplyr::filter(varname %in% names(df)) %>%
  dplyr::filter(ordering == "ordered")

df <- df %>%
  # Ordered variables as ordinal factors
  dplyr::mutate(across(.cols = ordinal_vars_mydata$varname,
                        ~factor(., ordered = TRUE))) %>%
  # Everything else as unordered factors
  dplyr::mutate(across(.cols = -ordinal_vars_mydata$varname,
                        ~factor(.)))
str(df)

```


```{r}
x <- df %>%
  select(-target, -X) %>%
  as.data.frame()

y <- df$target
```


```{r}
set.seed(2021)
inTrain <- createDataPartition(y, p = .80, list = FALSE)[,1]

x_train <- x[ inTrain, ]
x_test  <- x[-inTrain, ]

y_train <- y[ inTrain]
y_test  <- y[-inTrain]

colnames(x_train)
```


# Running an ordinal variant of a decision tree (rpartScore) using the top features found, with a grid search CV

```{r}
# # Define the control using a random forest selection function
# control <- rfeControl(functions = rfFuncs, # random forest
#                       method = "repeatedcv", # or just cv
#                       repeats = 10, # number of repeats
#                       number = 10) # the number of folds
```


```{r}
tictoc::tic()
cl <- makePSOCKcluster(10)
registerDoParallel(cl)

set.seed(2021)

# Specify 10 fold cross-validation
ctrl_cv <- trainControl(method = "repeatedcv",
                        search="grid",
                        number = 10,
                        repeats=10,
                        timingSamps = 5,
                        # seeds = c(1:101)
                        )
# Predict income using decision tree
dec_mod <- train(x=x_train,
                 y=y_train,
                    method = "rpartScore",  
                    trControl = ctrl_cv,
                    tuneGrid = expand.grid(
                      cp = seq(0,1,0.1),
                      split = c("abs", "quad"),
                      prune = c("mc", "mr")
                      )

                 )

stopCluster(cl)
tictoc::toc()
```

```{r}
registerDoSEQ()
```


```{r}
varimp_data <- varImp(dec_mod)
varimp_data
```


```{r}
dec_mod$results
```

```{r}
ggplot(dec_mod, "Accuracy")
```



```{r}
# Post prediction
postResample(predict(dec_mod, x_test), y_test)
```


```{r}
prediction_tibble <- tibble("target"=y_test,
       "prediction"=predict(dec_mod, x_test))
prediction_table <- table(prediction_tibble)
cfm <- as_tibble(prediction_table)
plot_confusion_matrix(cfm, 
                      target_col = "target", 
                      prediction_col = "prediction",
                      counts_col = "n")
```

```{r, fig.height=10, fig.width=15}
fancyRpartPlot(dec_mod$finalModel)
```


```{r}
pred_df <- data.frame(target=as.numeric(y_test),
           prediction=as.numeric(predict(dec_mod, x_test)),
           row.names = rownames(x_test))

pred_df$correct_or_not <- pred_df$target + pred_df$prediction

zero_ids <- rownames(pred_df[pred_df[, "correct_or_not"] == 2,])
one_ids <- rownames(pred_df[pred_df[, "correct_or_not"] == 4,])

length(zero_ids)
length(one_ids)
```

```{r}
df[zero_ids, ]
df[one_ids, ]
```

```{r}
top_features <- rownames(head(varimp_data$importance, 3))
# top_features <- c("behaviour_indoors_nonhouseholders", "behaviour_close_contact", "intention_indoor_meeting")
```

```{r}
# df$demographic_gender <- factor(df$demographic_gender)
# df <- data.frame(apply(df, 2, factor))
```

```{r}
# df %<>%
#        mutate_each_(funs(factor(.)),top_features)
# # str(df)
```


```{r}
x <- df[top_features]

y <- factor(df$target)

```

```{r}
set.seed(2021)
inTrain <- createDataPartition(y, p = .80, list = FALSE)[,1]

x_train <- x[ inTrain, ]
x_test  <- x[-inTrain, ]

y_train <- y[ inTrain]
y_test  <- y[-inTrain]

colnames(x_train)
```

```{r}
cl <- makePSOCKcluster(10)
registerDoParallel(cl)

set.seed(2021)

# Specify 10 fold cross-validation
ctrl_cv <- trainControl(method = "repeatedcv",
                        search="grid",
                        number = 10,
                        repeats=10,
                        timingSamps = 5,
                        # seeds = c(1:101)
                        )
# Predict income using decision tree
dec_mod <- train(x=x_train,
                 y=y_train,
                    method = "rpartScore",  
                    trControl = ctrl_cv,
                    tuneGrid = expand.grid(
                      cp = seq(0,1,0.1),
                      split = c("abs", "quad"),
                      prune = c("mc", "mr")
                      )

                 )

stopCluster(cl)
```

```{r}
registerDoSEQ()
```

```{r}
# Post prediction
postResample(predict(dec_mod, x_test), y_test)
```

```{r}
prediction_tibble <- tibble("target"=y_test,
       "prediction"=predict(dec_mod, x_test))
prediction_table <- table(prediction_tibble)
cfm <- as_tibble(prediction_table)

```


```{r}
plot_confusion_matrix(cfm, 
                      target_col = "target", 
                      prediction_col = "prediction",
                      counts_col = "n")
                      
                      
```

```{r, fig.height=10, fig.width=15}
fancyRpartPlot(dec_mod$finalModel)
```


```{r}
varImp(dec_mod)
```


```{r}
ggplot(data=df, aes(x=X, y=likert_5_options_10, color=target)) + geom_point()
```

```{r}
ggplot(data=df, aes(x=X, y=likert_5_options_30, color=target)) + geom_point()
```

```{r}
dec_mod
```

```{r}
dec_mod$bestTune
dec_mod$finalModel
```

